
FROM busybox as base
FROM busybox as builder

COPY --from=base . /rootfs

RUN echo "nameserver 8.8.8.8" > /rootfs/etc/resolv.conf
RUN cat /rootfs/etc/resolv.conf

COPY --from=quay.io/luet/base:latest /usr/bin/luet /usr/bin/luet

COPY --from=quay.io/kairos/framework:master_ubuntu . /rootfs

# Avoid to accidentally push keys generated by package managers
RUN rm -rf /rootfs/etc/ssh/ssh_host_*

FROM scratch as rootfs

COPY --from=builder /rootfs/ .

FROM rootfs
# Additional os specific things

